export const APP_CHROME_CONTENT = {
  labels: {
    theme: 'Theme',
    language: 'Language',
    user: 'User',
    noUser: 'No User',
    help: 'Help',
    helpSymbol: '?',
    switchUser: 'Switch User',
    mergeUsers: 'Merge Users',
    updateProfile: 'Update Profile',
    chooseUser: 'Choose User',
    noUsers: 'No Users',
    createUser: 'Create User',
    deleteUser: 'Delete User',
    clearData: 'Clear Data',
    danger: 'Danger',
    editProfile: 'Edit Profile',
    close: 'Close',
    closeWithoutSaving: 'Close Without Saving',
    saveChanges: 'Save Changes',
    save: 'Save',
    create: 'Create',
    displayName: 'Display Name',
    pronouns: 'Pronouns',
    subject: 'Subject',
    object: 'Object',
    status: 'Status',
    show: 'Show',
    emoji: 'Emoji',
    text: 'Text',
    bio: 'Bio',
    avatar: 'Avatar',
    cropSize: 'Crop Size',
    cropX: 'Crop X',
    cropY: 'Crop Y',
    applyCrop: 'Apply Crop',
    upload: 'Upload',
    delete: 'Delete',
    mask: 'Mask',
    noMask: 'No mask',
    deleteMask: 'Delete Mask',
    keepUser: 'Keep User',
    mergeTheseUsers: 'Merge These Users',
    importFromJson: 'Import from JSON',
    exportToJson: 'Export to JSON',
    continueEditing: 'Continue Editing',
    unsavedChanges: 'Unsaved Changes',
    closeProfile: 'Close Profile?',
    cancel: 'Cancel',
    confirm: 'Confirm',
  },
  aria: {
    openHelp: 'Open help',
    userActionModal: 'User action modal',
    unsavedProfileConfirmation: 'Unsaved profile confirmation',
    confirmationModal: 'Confirmation modal',
    customSubjectPronoun: 'Custom subject pronoun',
    customObjectPronoun: 'Custom object pronoun',
  },
  placeholders: {
    emoji: 'Emoji',
    statusText: 'Status text',
    noBio: 'No bio yet.',
  },
  messages: {
    noBio: 'No bio yet.',
    mergeUsers:
      'Diaries from selected users will move into the user you keep. The selected users will be removed.',
    emptyUsers:
      'There are no local users. Create a user or import from JSON.',
    unsavedProfile:
      'This profile has unsaved changes. Close without saving?',
    deleteUserFirstStepTitle: 'Delete User',
    deleteUserSecondStepTitle: 'Confirm Delete',
    clearDataFirstStepTitle: 'Clear Data',
    clearDataSecondStepTitle: 'Confirm Clear',
    deleteUserSecondStep:
      'This cannot be undone. Confirm one more time to delete this user.',
    clearDataFirstStep: 'Clear all local data in this browser?',
    clearDataSecondStep:
      'This cannot be undone. Confirm one more time to clear all local data.',
    deleteUserFirstStepPrefix: 'Delete',
    deleteUserFirstStepSuffix: "and this user's entries?",
    mergeRequiresTwoUsers: 'At least two users are required to merge.',
    mergeSelectionRequired:
      'Choose a target user and at least one source user.',
    mergeFailed: 'Failed to merge users.',
    avatarCropRequired: 'Apply the avatar crop before saving.',
    profileUpdateFailed: 'Failed to update profile.',
    avatarCropFailed: 'Failed to crop avatar.',
    avatarMaskPending:
      'Apply the crop first. The mask will be generated automatically.',
  },
  alt: {
    logo: 'Personal Diary logo',
    cropSourceSuffix: 'crop source',
    maskSuffix: 'mask',
  },
} as const;
