export const PERSONAL_DATA_HOME_CONTENT = {
  labels: {
    newDiary: 'New Diary',
    navigation: 'Navigation',
    notebookTitle: 'My Diary Notebook',
    loading: 'Loading...',
    noEntries: 'No entries yet.',
    edit: 'Edit',
    delete: 'Delete',
    filters: 'Filters',
    mood: 'Mood',
    range: 'Range',
    anxiety: 'Anxiety',
    energy: 'Energy',
    writtenDuring: 'Written During',
    all: 'All',
    timeZoneBasis: 'Time Zone Basis',
    close: 'Close',
    title: 'Title',
    highlight: 'Highlight',
    trouble: 'Trouble',
    bodyFeeling: 'Body Feeling',
    body: 'Body',
    level: 'Level',
    danger: 'Danger',
    cancel: 'Cancel',
    confirm: 'Confirm',
    deleteDiary: 'Delete Diary?',
    unsavedChanges: 'Unsaved Changes',
    noUnsavedChanges: 'No Unsaved Changes',
    closeDiary: 'Close Diary?',
    continueEditing: 'Continue Editing',
    closeWithoutSaving: 'Close Without Saving',
    createDraftTitle: 'New Diary',
    updateDraftTitle: 'Edit Diary',
    createDraftEyebrow: 'Diary',
    updateDraftEyebrow: 'Update',
    createDraftSubmit: 'Save',
    updateDraftSubmit: 'Update',
  },
  aria: {
    expandNavigation: 'Expand navigation',
    collapseNavigation: 'Collapse navigation',
    collapseFilters: 'Collapse filters',
    expandFilters: 'Expand filters',
    desktopLargeModal: 'Desktop large modal',
    mobileLargeModal: 'Mobile large modal',
    deleteDiaryConfirmation: 'Delete diary confirmation',
    unsavedDiaryConfirmation: 'Unsaved diary confirmation',
  },
  placeholders: {
    untitledDiary: 'Untitled Diary',
  },
  messages: {
    thisDiary: 'this diary',
    diaryFromPrefix: 'the diary from',
    draftHelper:
      'Add only the parts that matter today. Empty optional fields stay out of the saved entry.',
    deleteDiarySuffix: 'This cannot be undone.',
    unsavedDiary: 'This diary has unsaved changes. Close without saving?',
    emptyDraft: 'Add at least one field before saving.',
    missingUpdateSelection: 'No diary is selected for update.',
    diarySaveFailed: 'Failed to save diary.',
    diaryNotFound: 'Diary not found.',
  },
} as const;
